apiVersion: v1
kind: Service
metadata:
  name: crud-app-service
spec:
  selector:
    app: crud-app-app
  ports:
    - name: django-crud
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30036 
  type: NodePort
