# Generated by Django 4.1.7 on 2023-03-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksdb',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
